# Generated by Django 4.2.1 on 2023-05-31 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=75)),
                ('password', models.CharField(max_length=128)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izenburua', models.CharField(max_length=100)),
                ('zuzendaria', models.CharField(max_length=60)),
                ('urtea', models.IntegerField()),
                ('generoa', models.CharField(max_length=2)),
                ('sinopsia', models.CharField(max_length=500)),
                ('bozkak', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FilmaBozkatzailea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erabiltzailea_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GogokoFilmak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filmak.filma')),
                ('filma_gogokoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filmak.filmabozkatzailea')),
            ],
        ),
        migrations.CreateModel(
            name='Erabiltzailea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Filmak.authuser')),
                ('filma_bozkatzailea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Filmak.filmabozkatzailea')),
            ],
        ),
    ]
