# Generated by Django 4.2.1 on 2023-06-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Filmak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filma',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Filmak.authuser'),
        ),
    ]
